<?php
/**
 * Plugin Name: Status Tracker
 *
 */
 
function fsd_page_status_tracker_admin_menu() {
    // Create a new admin page for our app.
    // Includes an empty div with unique ID for React app entry point
    add_menu_page(
        'Status Tracker',
        'Status Tracker',
        'manage_options',
        'fsd-page-status-tracker',
        function () {
            echo '
            <h2>Page Status Tracker</h2>
            <div id="fsd-page-status-tracker"></div> 
        ';
        },
        'dashicons-chart-bar',
        3
    );
}
 
add_action( 'admin_menu', 'fsd_page_status_tracker_admin_menu' );
 
function fsd_load_custom_wp_admin_scripts( $hook ) {
    // Load only on our plugin page - ?page=fsd-page-status-tracker.
    if ( 'toplevel_page_fsd-page-status-tracker' !== $hook ) {
        return;
    }
 
    // Automatically load imported dependencies and assets version - generated by @wordpress/scripts.
    $asset_file = include plugin_dir_path( __FILE__ ) . 'build/index.asset.php';
 
    // Enqueue CSS dependencies.
    foreach ( $asset_file['dependencies'] as $style ) {
        wp_enqueue_style( $style );
    }
 
    // Load our app.js - reference version and dependencies from asset file
    wp_register_script(
        'fsd-page-status-tracker',
        plugins_url( 'build/index.js', __FILE__ ),
        $asset_file['dependencies'],
        $asset_file['version']
    );
    wp_enqueue_script( 'fsd-page-status-tracker' );

    wp_localize_script( 'fsd-page-status-tracker', 'localizedData',
        array( 
            'homeUrl' => home_url(),
        )
    );
 
    // Load our style.css.
    wp_register_style(
        'fsd-page-status-tracker',
        plugins_url( 'style.css', __FILE__ ),
        array(),
        $asset_file['version']
    );
    wp_enqueue_style( 'fsd-page-status-tracker' );
}
 
add_action( 'admin_enqueue_scripts', 'fsd_load_custom_wp_admin_scripts' );


function fsd_register_meta() {
    register_meta('post', '_fsd_page_status', array(
      'show_in_rest' => true,
      'type' => 'integer',
      'single' => true,
      'auth_callback' => function() { 
        return current_user_can('edit_posts');
      }
    ));
  }
add_action('init', 'fsd_register_meta');


